# Generated by Django 2.2.6 on 2020-07-12 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20200712_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='project',
            name='name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='year',
        ),
    ]
