# Generated by Django 2.2.6 on 2020-07-12 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_education'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Education',
        ),
    ]
