# Generated by Django 2.2.6 on 2020-07-13 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20200713_1541'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
