# Generated by Django 2.2.6 on 2020-07-12 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills',
            old_name='progress',
            new_name='percentage',
        ),
    ]
