# Generated by Django 2.2.6 on 2020-07-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_remove_skills_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='lang',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='skills',
            name='skill',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
