# Generated by Django 2.2.6 on 2020-07-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=100)),
            ],
        ),
    ]
